### ISSUE TITLE
Add a new example with Redwood JS

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-auth-react#144]

**Comment by NkxxkN** [comment]
Moving the conversation from the PR to this issue:

Not sure how to connect SuperTokens Node middleware system with Redwood functions as there does not seem to be any req, res objects accessible.

We might have to bypass all the logic using request, response, and return an object instead of sending the response?

**Comment by rishabhpoddar** [comment]
Closing in favour of https://github.com/supertokens/supertokens-core/issues/129
