### ISSUE TITLE
Support for vue and other frontend frameworks

### ISSUE THREAD

**Issue by tobiasdiez** [supertokens/supertokens-auth-react#239]
I was looking into integrating supertokens in a vue project and was struggling to find a starting point. What I'm missing is a high-level frontend library that handles all the supertokens-related stuff (i.e. calling the right api endpoint). It seems that this is rather buried deep down in this module, e.g https://github.com/supertokens/supertokens-auth-react/blob/b6f0f7a418e76dd27c7148d359a04f8e7158d23c/lib/ts/recipe/emailpassword/components/features/signInAndUp/api.ts#L32. Is there a way to extract this, and reuse it?

**Comment by rishabhpoddar** [comment]
We have an SDK for vanilla JS called supertokens-website. But at the moment, that only works with the session recipe. We do plan on extracting as much of the react SDK into the supertokens-website SDK so that that code is reusable across various framework specific SDKs. 

But we don't have a specific timeline on when we will do that.

**Comment by rishabhpoddar** [comment]
Closing in favour of https://github.com/supertokens/for-zenhub/issues/28

**Comment by tobiasdiez** [comment]
This link is not working, is there any plans to make this repo public soon?

**Comment by rishabhpoddar** [comment]
Yea. We are working on this: https://github.com/supertokens/supertokens-web-js/tree/0.0 which should provide helper functions for all recipes which can be used in non-react apps. Note that it won't provide a UI though.

Should be out in a few weeks.

**Comment by tobiasdiez** [comment]
Okay, thanks! Looking forward to it!
