### ISSUE TITLE
Code review for branch 0.0 - 5th Nov 2020

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-auth-react#27]
## Related to previous code review (https://github.com/supertokens/supertokens-auth-react/issues/20)
- [x] The `index.ts` of emailpassword does not does not export the components as part of the default export. Is that intentional? This means that users cannot do `<EmailPassword.SignInAndUp />`
- [x] Why do you have `export { SessionAPIWrapper };` in the `index.ts` of session recipe?
- [x] `getMatchingComponentForRouteAndRecipeId` should take path as NormalisedURLPath. Not as a string. You want to convert this class to a string as late as possible, and only if absolutely necessary.
- [x] The below 
   > (My comment) getMatchingComponentForRouteAndRecipeId is written in a way that if a rId is provided in the URL, but that doesn't match any recipe, then we will treat it as if rId is not there is not there in the URL. Is this expected?

   > (Your reply) "Yes that's what we decided in our previous discussion around routing. If no rid is provided, or if rid is unknown we want to use the first recipe feature that matches."

   Are you sure we had this conversation? Because on the backend, if the `rId` is there, but it not matching any route, then I pass the request to the user.

- [x] If we are allowing users to change the background for the default routes, then where will that go? If we allow them to do it via style in the init, what if they give a different colour for sign up and sign in?

- [x] The below
   > validateFormOrThrow in utils.ts does not throw any error.

   > It actually does throw if length is different as per our conversation.

   Yes, but the name suggests that if the form is valid, then it will not throw an error, else it will. Which means, as a consumer of this function I would not care about the return type.

- [x] It would be nice to move the API calls in SignInAndUp (and other components) to a different file that only contains API calls.

- [x] Does `fetch` throw an error in case the status code is >= 300?

## New issues
- [x] `onSuccessRedirectURL` in the config can be a full URL right (in case of multi-tenancy)? In that case, you do not want to normalise it with `NormalisedURLPath`. Perhaps there is no normalisation for this value that is required? (This applies to signInUp and to resetPassword feature)

- [x] When creating the `defaultSignInFields` in `utils.ts` (line 146), I think you forgot to add the email validator? If not that, you added the default password validator, overriding the user's password validator?

- [x] I feel the way the signIn form fields has been made can have bugs cause it's hard to understand for the following reasons (feel free to ignore this if you are very confident that your code regarding this is bug free):
   - Using reduce
   - Doing reduce on signup form fields, then doing a reduce on user's input form fields, then merging the two. Can this be made simpler somehow?

- [x] You are doing an implicit check with `if (config.resetPasswordURL) {` in `utils.ts`. What is `resetPasswordURL === ""`? Then is `if ("") === if (true)`. **Please, no more implicit checks.** Which also means no more of `config.style || {}`, and no more `if (this.props.onHandleForgotPasswordClicked)` etc.. 

- [x] I may be wrong, but the `normaliseResetPasswordUsingTokenFeature` does not seem to take the email and password validators from sign up.

- [x] There are two places you use `Object.assign`, but everywhere else you use the spread operator. I prefer you stick on one style of coding. 

- [x] I am not 100% sure about this, but extending component classes with `PureComponent` may be better than doing so with `Component`. `PureComponent` does a shallow comparison of state and props to check if a render is needed which may be more efficient than `Component` which always returns `true` by default.

- [x] When setting state in components that are class based, you should use `this.setState(oldState => {...})` method. This is a more reliable method since you are guaranteed to mutate the "actual current state" in case the setState runs after a couple other `setStates`.

- [x] The return type of `signUpAPI` (line 197 in SignInAndUp) (and other similar functions) is very confusing. Please rename `response` and `responseJson` to something better.

- [x] The `FormBase` component is not using [controlled input](https://reactjs.org/docs/forms.html#controlled-components). I'm not sure what the benefit of that is, but maybe it's worth doing that?

- [x] The state for SignInAndUp can be improved from a type point of view (Not sure if the below will exactly work according to your logic, but something like this where you divide the state into clear distinct sub types based on the state of the form):
   ```
   {
      status: "LOADING"
   } | {
      status: "NOT_SUBMITTED",
   } | {
      status: "SUBMITTED",
      user: User,
      responseJson: any
   }
   ```
   - From the types, we know that if the status is LOADING, then no other state matters. Your render function will be forced to check the status first and render correctly = no bugs
   - If the form has not been submitted yet, then there will be no user and responseJson object. Again, your functions will be forced to make this check = no bugs.
   - If the form has been submitted, then there MUST be a user and responseJson object.
   - Try doing something similar for all the components if possible. It makes everything more clear.

- [x] Since `supertokens-website` is in the `dependencies` in package.json, you can use a normal import statement for it in `session.ts`

- [x] `addAxiosInterceptors`, `setAuth0API` and `getAuth0API` are missing from the session recipe. 

- [x] Is all the UI responsive for tablet, mobile, 4k screens etc..?

**Comment by NkxxkN** [comment]
New pull request https://github.com/supertokens/supertokens-auth-react/pull/29/files



> - [ ] The `index.ts` of emailpassword does not does not export the components as part of the default export. Is that intentional? This means that users cannot do `<EmailPassword.SignInAndUp />`
> - [ ] Why do you have `export { SessionAPIWrapper };` in the `index.ts` of session recipe?

I though that was what you meant in your previous review. 
This  `<EmailPassword.SignInAndUp />` make more sense to me now. Fixed in next PR coming.

> - [ ] `getMatchingComponentForRouteAndRecipeId` should take path as NormalisedURLPath. Not as a string. You want to convert this class to a string as late as possible, and only if absolutely necessary.

I did it for the instance method and didn't for the class instance at the time but can't remember why. I might have thought this was a method that was exposed to the end user. Anyway,  fixed in next PR coming.

> - [ ] The below 
   > (My comment) getMatchingComponentForRouteAndRecipeId is written in a way that if a rId is provided in the URL, but that doesn't match any recipe, then we will treat it as if rId is not there is not there in the URL. Is this expected?

   > (Your reply) "Yes that's what we decided in our previous discussion around routing. If no rid is provided, or if rid is unknown we want to use the first recipe feature that matches."

>   Are you sure we had this conversation? Because on the backend, if the `rId` is there, but it not matching any route, then I pass the request to the user.

That's what we mentioned here https://github.com/supertokens/supertokens-auth-react/issues/12 and decided to make it consistent between `react-router-dom` and the no router one.


 > validateFormOrThrow: Yes, but the name suggests that if the form is valid, then it will not throw an error, else it will. Which means, as a consumer of this function I would not care about the return type.

Ooh ok from that prespective that makes sense. Renaming to `validateForm`.

> - [ ] If we are allowing users to change the background for the default routes, then where will that go? If we allow them to do it via style in the init, what if they give a different colour for sign up and sign in?

Changing the background of the page happens in their CSS. Changing the background of the login/signup container can happen in two places. If they want to change the background for all, they can update the palette background property. If they want to update the background for only one, or change it for both, they can do it by updating the backgroundColor property of the container style: 

```
SuperTokens.init({
  appInfo: {
  },
  recipeList: [
    EmailPassword.init({
      signInAndUpFeature: {
        signUpForm: {
          style: {
            container: {
              background: "red"
            }
         },
         signInForm: {
           style: {
             container: {
               background: 'blue'
             }
          }
       }
     })
    ]
});
```
       

## New issues
> - [ ] `onSuccessRedirectURL` in the config can be a full URL right (in case of multi-tenancy)? In that case, you do not want to normalise it with `NormalisedURLPath`. Perhaps there is no normalisation for this value that is required? (This applies to signInUp and to resetPassword feature)



> - [ ] When creating the `defaultSignInFields` in `utils.ts` (line 146), I think you forgot to add the email validator? If not that, you added the default password validator, overriding the user's password validator?

What happens there is that we reuse the signupForm formFields. No need to add the email validator since it's already present in the signUpForm formFields.
We want to override the password validator (the default one or one provided by the user), with the `defaultLoginPasswordValidator` which actually only checks if the password length is more than 0. 

This is related to https://github.com/supertokens/supertokens-auth-react/issues/21

> - [ ] I feel the way the signIn form fields has been made can have bugs cause it's hard to understand for the following reasons (feel free to ignore this if you are very confident that your code regarding this is bug free):
   - Using reduce
   - Doing reduce on signup form fields, then doing a reduce on user's input form fields, then merging the two. Can this be made simpler somehow?

In the second case, `reduce` replaces subsequent `filter` and `map` in order to reduce the number of loops.
I agree that time complexity is totally not a problem here, for readability purposes, filter and map would be better, so I updated it in next PR.

In the first case, we could first filter by email and password, but then we want to make two different operations for email and password, so the map would be as complex as the reduce so we will keep it that way.

Merging them happens with the generic method `mergeFormFields`. I thought about extracting `email` and `password` fields and doing manual merge but that would in the end add complexity in the end as we would bypass the default generic `mergeFormFields` method.

> - [ ] You are doing an implicit check with `if (config.resetPasswordURL) {` in `utils.ts`. What is `resetPasswordURL === ""`? Then is `if ("") === if (true)`. **Please, no more implicit checks.** Which also means no more of `config.style || {}`

Fixed. eslint does not catch this and  I didn't find any way to catch it with the linter so I'm going to be extra cautious now.

> - [ ] I may be wrong, but the `normaliseResetPasswordUsingTokenFeature` does not seem to take the email and password validators from sign up.

Good catch!
Fixed in next PR. 

> - [ ] There are two places you use `Object.assign`, but everywhere else you use the spread operator. I prefer you stick on one style of coding. 

Typescript throws an error: `'y' is specified more than once, so this usage will be overwritten. This spread always overwrites this property.` in the following case:

```
const a = { x: 1, y: 2};
const b = { y: 3, z: 4};
const c = {...a,...b}
```


When overwritting is actually exactly what we want to achieve in our case. There is a debate in the typescript team on wether this is right or wrong but in the ,meantime it keeps throwing.
I'd very much like to keep the spread operator everywhere else as it is way more flexible than Object.assign. I managed to update the ` @emotion/core` type from CSSInterpolation to CSSObject to make it work. CSSObject is more restrictive and correspond to our case better.

 Regarding the other place where it happened, I'm not using the getDefaultPasswordFormFields anymore.

> addAxiosInterceptors, setAuth0API and getAuth0API are missing from the session recipe.

Done.

> The FormBase component is not using controlled input. I'm not sure what the benefit of that is, but maybe it's worth doing that?

Reading on official docs and https://medium.com/tech-tajawal/controlled-and-uncontrolled-components-in-react-6d5f260b46dd: 
 - controlled components let react control the input value ( as opposed to the HTML DOM) => We don't really care about this as we have no intention to remove the inputs on button clicks, or to replace some characters with others etc...

```
you can use the controlled component when you create
 - Form validation so you always need to know the value of the input when typing to check if it’s a valid character or not!
 - Disable the submit button unless all fields have valid data
 - If you have a specific format like the credit card input

But if you don’t need any of that and think that the uncontrolled will be simpler for you, go for it.
```

In my mind, I'm thinking of it as two ways binding vs one way binding. Currently we only need one way binding. If we start to do more complex things (like updating the current value with a new value in the validate methods), then it will be time to revisit.

> I am not 100% sure about this, but extending component classes with PureComponent may be better than doing so with Component. PureComponent does a shallow comparison of state and props to check if a render is needed which may be more efficient than Component which always returns true by default.

Sounds good, I replaced all and it seems to be working well.

> Does fetch throw an error in case the status code is >= 300?

Fetch throws >= 400
Axios throws >= 300

In `httpRequest.ts` we are throwing above 300 even though we use fetch. Resulting in "Something went wrong Please try again" error. So in our docs we should mention that if using props callback methods and fetch, make sure that you throw an exception if status code is above 300.

> Is all the UI responsive for tablet, mobile, 4k screens etc..?

I developed mainly with Chrome. I always test with different resolutions using chrome dev tools.

**Galaxy Fold** (Smallest)
![image](https://user-images.githubusercontent.com/5072452/98242832-57ced080-1f6d-11eb-94a3-35dded0ebdf4.png)


**IPHONE 5/SE** 
![image](https://user-images.githubusercontent.com/5072452/98241334-1806e980-1f6b-11eb-9bef-c65bd4f91ac6.png)

**Moto G4**
![image](https://user-images.githubusercontent.com/5072452/98240716-1f79c300-1f6a-11eb-8e2c-d324c3c6ba07.png)

**Galaxy S5**
![image](https://user-images.githubusercontent.com/5072452/98240941-7ed7d300-1f6a-11eb-9994-a7bf3cc82317.png)

**Pixel 2**
![image](https://user-images.githubusercontent.com/5072452/98240978-8b5c2b80-1f6a-11eb-88cb-d346ec94e2c5.png)

**Iphone X**
![image](https://user-images.githubusercontent.com/5072452/98241065-adee4480-1f6a-11eb-942f-4b3a0d408dbe.png)

**IPad PRO**
![image](https://user-images.githubusercontent.com/5072452/98242686-20602400-1f6d-11eb-9a51-b8a6c654e968.png)

**Surface Duo**

![image](https://user-images.githubusercontent.com/5072452/98242889-6a490a00-1f6d-11eb-8c0e-a883ff2600d6.png)


**My personal display 1920*1080*** 
![image](https://user-images.githubusercontent.com/5072452/98243524-5d78e600-1f6e-11eb-8566-9c00ff2d273e.png)


 Also checked on my phone after setting up ngrok instances, and did a less in depth testing with Firefox, safari and opera too

**Safari**
![image](https://user-images.githubusercontent.com/5072452/98242988-92d10400-1f6d-11eb-814f-ef37df03961b.png)

**Opera**
![image](https://user-images.githubusercontent.com/5072452/98243452-43d79e80-1f6e-11eb-8cb7-9bb48739b2b8.png)


**Firefox**
![image](https://user-images.githubusercontent.com/5072452/98244084-26570480-1f6f-11eb-9f69-631fd55bbf15.png)


I also used http://whatismyscreenresolution.net/multi-screen-test to test 2k and 4k which worked well!

Catched a bug with routing happening only on Firefox => `/auth/reset-password` is not working. Issue here https://github.com/supertokens/supertokens-auth-react/issues/28
Found a fix. 


> The return type of signUpAPI (line 197 in SignInAndUp) (and other similar functions) is very confusing. Please rename response and responseJson to something better.

I update response to `normalisedAPIResponse` as it is indeed not exactly the API response, but a transformed response based on the API response. I'm keeping `responseJson` as this is exactly the name of the object that we expose in the props callbacks. If we'd like to rename it here, we should also rename in the props callbacks and in the docs. 
Let me know if we should revisit this.

**Comment by rishabhpoddar** [comment]
> That's what we mentioned here #12 and decided to make it consistent between react-router-dom and the no router one.

Oh! There I meant that if the `rId` is missing, only then we should match on the first route. I still think that if the `rId` is there but not matched, then we should let the user's routes handle it. However, I realise that this may not be possible, in which case, it's fine the way it is :)

> I am not 100% sure about this, but extending component classes with PureComponent may be better than doing so with Component. PureComponent does a shallow comparison of state and props to check if a render is needed which may be more efficient than Component which always returns true by default.

> Sounds good, I replaced all and it seems to be working well.

If you do this, make sure the state is always immutable. That is, when you change the state, you should always create a new object and copy in the state from the older one.

> I developed mainly with Chrome. I always test with different resolutions using chrome dev tools.

Please also make sure to test in firefox and safari in different resolutions. Since sometimes the UI works fine in one, but breaks in others. This happens especially with Safari.

On some screens (Galaxy S5, Moto G4), the form looks a shifted to the right.

> I update response to normalisedAPIResponse as it is indeed not exactly the API response, but a transformed response based on the API response. I'm keeping responseJson as this is exactly the name of the object that we expose in the props callbacks. If we'd like to rename it here, we should also rename in the props callbacks and in the docs.
Let me know if we should revisit this.

No need to rename it :)

---------------

- [ ] The way to use the functional `setState` is as follows:
   ```js
   this.setState((oldState) => {
      return  {
         ...oldState,
         someField: {
            ...oldState.someField,
            fieldToUpdate: updatedValue
         }
      }
   })
   ```

   if you are changing something **only** based on the current state (like toggling sign up / in UI):
   ```js
   this.setState((oldState) => {
      return  {
         ...oldState,
         showSignUpUI: !oldState.showSignUpUI
      }
   })
   ```

   if you are changing state assuming a certain current state:
   ```js
   this.setState((oldState) => {
      if (oldState.status !== "LOADING") {
         return oldState;
      }
      return  {
         ...oldState,
         someFieldToUpdate: updatedValue // this field only exists if the oldState.status !== "LOADING"
      }
   })
   ```
   
   The above prevents UI glitches in case quick user inputs that cause many state changes

**Comment by NkxxkN** [comment]
> On some screens (Galaxy S5, Moto G4), the form looks a shifted to the right.

True! I just noticed that. It's because the screen is so small that adding a margin makes it shift to the right. I'll make sure to add media-queries to reduce the left margin even more for small screens.
