### ISSUE TITLE
Can i pass additional params to /auth/authorisationurl?

### ISSUE THREAD

**Issue by devkiran** [supertokens/supertokens-auth-react#352]
I need something like this`/auth/authorisationurl?thirdPartyId=custom-provider-id&tenant=abc.com`. Is this possible right now?

**Comment by rishabhpoddar** [comment]
Yea. You can use our preAPIHook and change the request object to add additional params as shown here: https://supertokens.io/docs/thirdpartyemailpassword/advanced-customizations/frontend-hooks/pre-api

You will want to modify the `} else if (action === "GET_AUTHORISATION_URL") {` block from the code snippet above.

In the backend, to consume the extra query param (the `tenant` one), you should have a look at our API override section: https://supertokens.io/docs/thirdpartyemailpassword/advanced-customizations/apis-override/usage, and you want to override the `authorisationUrlGET` function.

I am closing this issue for now since I assume that what you want is possible via the above. If not, please feel free to reopen it.

**Comment by devkiran** [comment]
Thanks, it worked!
