### ISSUE TITLE
Add receipe for passwordless + social login

### ISSUE THREAD

**Issue by jeremylynch** [supertokens/supertokens-auth-react#370]
Is this currently possible to achieve?

**Comment by rishabhpoddar** [comment]
We are working on this as well. Should be coming up soon.

**Comment by execreate** [comment]
This one is implemented, right? I can see `thirdpartypasswordless` in the code.

**Comment by rishabhpoddar** [comment]
@execreate yes. It is implemented. We even have docs for it: https://supertokens.com/docs/thirdpartypasswordless/introduction

It's just not officially released yet cause we have to change the [guides page](https://supertokens.com/docs/guides) to link to the docs. Otherwise it's all production ready.

**Comment by execreate** [comment]
@rishabhpoddar that's cool, thank you!

**Comment by rishabhpoddar** [comment]
This has been released. Closing it now.
