### ISSUE TITLE
Design issues with thirdpartypasswordless

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-auth-react#404]
@porcellus the implemented design is slightly different than what was intended from https://github.com/supertokens/main-website/issues/692

- [x] There is a missing header line between the title and the first social provider button
- [x] The gap between the Continue button and the powered by supertokens seems a lot more than what it is in just passwordless recipe
- [x] We need to make sure that the UI for if passwordless is disabled is === only third-party UI, and UI for if providers is empty === only passwordless recipe. Right now, the only discrepancies I can see are from the first two points in this list. But maybe you can catch more.
- [x] (This is not a UI issue) - the `signInUpFeature has a property called `linkSentScreenStyle`, which is strange, and also there is `linkClickedScreenFeature.style`. So this is duplicate. One of them needs to go. This is also true for just passwordless recipe.
- [x] You might want to rename `oAuthCallbackScreen` to `OAuthCallbackScreen`

**Comment by porcellus** [comment]
- Fixed it
- True, but this way it's consistent with thirdpartyemailpassword. Should I fix both?
- I'll check, maybe it'd be worth introducing storybook testing here.
- Those are not duplicates, they apply to different screens, also, we are using this structure in passwordless, because: 
  - `linkSentScreenStyle` applies to a screen that is basically just a separate state of the signInUp component
  -  We wanted the "subscreens" to have separate style objects
  -  `linkClickedScreen` is a different feature (and theme) component, so it has a separate prop in the root.
- We use camel case for props everywhere, shouldn't this be `oauthCallbackScreen` then? Also, this prop name comes from the third-party recipe, and I don't think we should update that.

**Comment by rishabhpoddar** [comment]
> True, but this way it's consistent with thirdpartyemailpassword. Should I fix both?

Uhmm. Let it be.

> Those are not duplicates

Oh yea.. sorry. I misread. Ignore that point.


> We use camel case for props everywhere, shouldn't this be oauthCallbackScreen then? Also, this prop name comes from the third-party recipe, and I don't think we should update that.

Ah i see. In third party it is called `oAuthCallbackScreen`. So let it be like this here too.
