### ISSUE TITLE
v0.4 Design revamp

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-auth-react#45]
<img width="1280" alt="Screenshot 2020-11-14 at 02 47 11" src="https://user-images.githubusercontent.com/2976287/99122113-bfe37d80-2623-11eb-8340-3919ed7d2ced.png">

**Comment by NkxxkN** [comment]
I used the designs from https://github.com/supertokens/supertokens-auth-react/issues/9

@mufassirkazi do you want to take a look and come up with a smaller size? currently `524px`.

**Comment by mufassirkazi** [comment]
Please change the max width from 524 px to 480 px

**Comment by rishabhpoddar** [comment]
@mufassirkazi please give a new design for a smaller UI with 480px.. This means smaller font size (maybe), lesser vertical padding, smaller input boxes etc.. After you have done that, only then will it be implemented.

**Comment by mufassirkazi** [comment]
## Changes
- Smaller UI: 420 px wide. 
- Input elements and buttons should be percent of the outer container (420 px). 
- Font sizes made smaller (14 px).
- The tick and the error icon made smaller. 
- Vertical padding decreased. 
- Border radius changes to 6px. 

## Sign up

- Default sign up form: https://zpl.io/aX0BwL8
- Email Id error: https://zpl.io/aMrOKdr
- Something went wrong: https://zpl.io/V0K3R9l

## Sign In

- Default sign in form: https://zpl.io/2GrZ9Em

## Reset password flows

- Default reset password screen: https://zpl.io/bz4mAw8
Email Id error: https://zpl.io/agwAPYA
Change your password screen: https://zpl.io/29rWoNw
Password error screen: https://zpl.io/amQp98A
Resend/ Change email screen: https://zpl.io/2ZZWjqd
Resent screen: https://zpl.io/V1P0zMm
Success screen: https://zpl.io/2p59noJ

**Comment by NkxxkN** [comment]
Will implement in `0.2.X`

**Comment by NkxxkN** [comment]
@mufassirkazi Can you take a look at my comment in https://github.com/supertokens/supertokens-auth-react/issues/22#issuecomment-731581119 (starting from **Password Managers inconsistencies section**), and propose a solution for error fields and password manager UI clashing.

We'd like a solution which allows for password manager helpers to be displayed in place of the svgs (error and success). So  the Error and Success indicators should be moved elsewhere (or removed?).

**Comment by mufassirkazi** [comment]
Updated designs in my last comment to address this issue

**Comment by NkxxkN** [comment]
We should remove the success emoji entirely:

**Before:**

![image](https://user-images.githubusercontent.com/5072452/100269217-7d407000-2f56-11eb-86a9-11586d9ff072.png)


**After**

![image](https://user-images.githubusercontent.com/5072452/100270109-db218780-2f57-11eb-868f-2d861bf63347.png)

**Comment by NkxxkN** [comment]
@mufassirkazi do we want to replace it somehow?

**Comment by mufassirkazi** [comment]
The new v2 designs will account for this. For now, you can have them removed. I had a talk with advait and we are changing the UI a fair bit so better if you don't work on the v2 designs that I have recently commented. I'll update you when they are done :)

**Comment by rishabhpoddar** [comment]
@mufassirkazi we should also have a way for users to see the password they have typed in the sign up / in form. Or maybe just in the sign up form.

**Comment by rishabhpoddar** [comment]
@mufassirkazi we also want to keep the sign up / sign in button enabled all the time, even if the input fields are empty. Becasue:
- On mobile, you do not have the feedback that it's disabled on hover.. the user may click on it, and nothing is happening...
- You may miss out filling a compulsory field, and wonder why the sign up button is disabled
- If the user clicks on sign up without entering correct and all info, then it will guide them towards correcting it.

**Comment by NkxxkN** [comment]
Agreed with Rishabh, I pushed for enabling/disabling button but this was a bad design decision. Let's keep it enabled all the time.

**Comment by rishabhpoddar** [comment]
There also needs to be feedback when sign up / sign in / Email me etc.. button

**Comment by rishabhpoddar** [comment]
https://github.com/supertokens/supertokens-auth-react/issues/96

**Comment by mufassirkazi** [comment]
# Design revamp

The whole UI has been made more smaller (font sizes, paddings, icon sizes changed)
New design solves problems caused by password managers
Show password functionality added




## Sign up

Normal state: https://zpl.io/aX0BwL8
Focus state: https://zpl.io/2vvwpKJ
Feedback state (checks)+ show password: https://zpl.io/a8XL186
Email id error: https://zpl.io/aMrOKdr
Something went wrong screen: https://zpl.io/V0K3R9l

## Sign In 

Normal state: https://zpl.io/2GrZ9Em
Sign out button: https://zpl.io/257QPlW
Error states, focus states, feedback state can be taken from the sign up form parts

## Reset password: 
Normal state: https://zpl.io/bz4mAw8
Change password: https://zpl.io/29rWoNw
Change password email id error: https://zpl.io/amQp98A
Email error: https://zpl.io/2p59noJ
Email sent: https://zpl.io/2ZZWjqd
Email resent: https://zpl.io/V1P0zMm
Success screen: https://zpl.io/29rWolW

**Comment by NkxxkN** [comment]
@mufassirkazi the "Show Password" suggests that it's a link (from a design perspective) and that clicking on it will redirect us somewhere. It seems a little bit confusing to me. 

Would be great to have something more similar to what the tech industry does 

![image](https://user-images.githubusercontent.com/5072452/103562006-ad1a5600-4eba-11eb-97c5-4c835d4ef60f.png)

But the challenge would be to have it so that it does not interfere with password managers.

Do you think it's worth trying to find something better?

**Comment by mufassirkazi** [comment]
Updated with eye icon as discussed
