### ISSUE TITLE
Commit package-lock.json

### ISSUE THREAD

**Issue by NkxxkN** [supertokens/supertokens-auth-react#66]
package-lock's purpose is to generate the exact same dependencies tree wherever the package is installed.
It is intended to be commited. See [Stackoverflow](https://stackoverflow.com/questions/44206782/do-i-commit-the-package-lock-json-file-created-by-npm-5)

Any reason why we are not commiting it atm?

**Comment by rishabhpoddar** [comment]
There is no reason for not committing it. We can add it to the commit.

**Comment by rishabhpoddar** [comment]
I'm not entirely sure what the purpose of package-lock.json is. Whenever I do `npm i`, it gets updated anyway and I get the latest version of the dependency if the version has a `^` in the `package.json` file. 

According to [this SO question](https://stackoverflow.com/a/45566871/3867175), the dependency versions are fixed only if there is no `^` or `~` in front of the version number (i.e. just `1.2.3`). In this case, what is the purpose of package-lock.json?

We want to achieve the following behaviour:
- For most dependencies of our libs, we want to stick to exact version numbers (no `^` or `~`), so that users get the same version of them, always
- For dependencies that are "trusted", we can use `^`
- For our dependencies, we can use `^`. So for example, `supertokens-auth-react` depends on `supertokens-website`. If there is a minor, non breaking fix in `supertokens-website`, we only want to update that, and all users of `supertokens-auth-react` should get the new version of `supertokens-website` on next `npm i`. We should not have to release a new version of `supertokens-auth-react`.

**Comment by NkxxkN** [comment]
The behaviour that you want make sense to me.

I took a quick look at the SO and I'm still confused...

Here is package-lock.json behaviour description after all those issues they had mentioned in that SO:

> - If you have a package.json and you run npm i we generate a package-lock.json from it.
> - If you run npm i against that package.json and package-lock.json, **the latter will never be updated**, even if the package.json would be happy with newer versions.
> - If you manually edit your package.json to have different ranges and run npm i and those ranges aren't compatible with your package-lock.json then the latter will be updated with version that are compatible with your package.json. Further runs of npm i will be as with 2 above.

This is not what seems to be happening.

Taking a look at few open source popular JS projects (React, webpack, nextJS), I never see any `package-lock.json`, but only `yarn.lock`.

I'll dig a little bit further into that one to make sure we take the right decision.

**Comment by rishabhpoddar** [comment]
Yes. Please let me know

**Comment by NkxxkN** [comment]
After further reading here is what I understood:

package-lock is not locking versions anymore in dev environment.. Running `npm install` will bump the versions as we witnessed. The role of package-lock is now to make sure that CI/CD are using the same versions (with the command `npm ci`).
This was intended so that bug fixes are still taken into account and version updates are still made.

**Comment by rishabhpoddar** [comment]
We will copy what other libraries do - they add package-lock
