### ISSUE TITLE
Empty Session.getAccessTokenPayloadSecurely()

### ISSUE THREAD

**Issue by sayhicoelho** [supertokens/supertokens-auth-react#664]
I'm trying to run this piece of code to get the authenticated user info but always returns an empty object.

![image](https://user-images.githubusercontent.com/8188365/224808155-5092bfdd-88db-423b-a1e3-4e2376690472.png)

`Session.getUserId()` is OK, but `Session.getAccessToken()` returns `undefined`.

My code:
![image](https://user-images.githubusercontent.com/8188365/224810509-5b78d0e2-32f0-4b19-b115-9bcf4a7ee109.png)

My console.log:
![image](https://user-images.githubusercontent.com/8188365/224808858-91826f08-aff8-4539-9ab6-787ea7fce880.png)

**Comment by rishabhpoddar** [comment]
Hey. 
- For the accessTokenPayload to have some values in it, you need to set it on the backend by overriding the createNewSession function
- When using cookie based auth, the getAccessToken function returns undefined - cause the frontend JS doesn't have access to the access token (since it's httpOnly cookie).

These don't seem to be issues with our SDKs, so closing this issue for now.
